### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by Ash258** [ScoopInstaller/Install#2]
Actual implementation should be respected. Upstream implementation is possible to set using environament varibles (not script parameters).
There is no need to set -InstallPath parameter, when you set `$env:SCOOP` (SCOOP_GLOBAL, SCOOP_CACHE)

https://github.com/scoopinstaller/install/blob/a4e4238c6b234626ae8d973529135e4398a1314b/install.ps1#L68-L73

All these variables should be surrounded by `if ($env:SCOOP) { $SCOOP_DIR = $env:SCOOP} else { $SCOOP_DIR = $ScoopDir}`

**Comment by h404bi** [comment]
https://github.com/lukesampson/scoop/blob/8dd09661b1db75d9bf3693045f3215f65a4bd945/lib/core.ps1#L6-L19

Currently, the installer doesn't save `$SCOOP_GLOBAL_DIR` and `$SCOOP_CACHE_DIR` to environment variables, so it's a bug.

This is a known issue. `$SCOOP_GLOBAL_DIR` and `$SCOOP_CACHE_DIR` variables haven't been used in the script currently. Although the actual implementation rely on them as environment variables, I was considering to save these three variables into `.scoop` config file instead of polluting environment variables. But this will require refactoring the core.

But yeah, exposing `$env:SCOOP` `$env:SCOOP_GLOBAL` and `$env:SCOOP_CACHE` make sense, the actual implementation should be respected.

**Comment by h404bi** [comment]
#3 should close this, but I would like to format all variables in `.scoop` file to `camelCase` naming, see https://github.com/scoopinstaller/install/pull/3/files#diff-00ded903b18eba5a23a1d8ec86c58e94R313

```
$SCOOP  ===> root
$SCOOP_CACHE  ===> cachePath
$SCOOP_GLOBAL ===> globalPath
lastupdate ===> lastUpdate

# more
show_update_log ===> showUpdateLog
SCOOP_REPO ===> scoopRepo
SCOOP_BRANCH ===> scoopBranch
```

@r15ch13 @Ash258 please take a review

**Comment by h404bi** [comment]
@Ash258 @r15ch13 new implementation in #4 , please take a review and give advice.
